### ISSUE TITLE
Add a responsive navigation bar to the website

### ISSUE THREAD

**Issue by srinjoy-26** [Techie-Tessie/Summer#4]
Add a navigation bar containing ,
- Home
- About Us
And can  @Mohasin-Haque you suggest some more fields??

please assign me.

**Comment by Tess314** [comment]
@srinjoy-26 That sounds like a great contribution! Some other field ideas could be 'Events' and 'Contact Us' :)

**Comment by srinjoy-26** [comment]
> @srinjoy-26 That sounds like a great contribution! Some other field ideas could be 'Events' and 'Contact Us' :)

are you a contributor? or a maintainer

**Comment by Tess314** [comment]
@srinjoy-26 A maintainer, I'm the CEO of Techie Tessie :)

**Comment by srinjoy-26** [comment]
> @srinjoy-26 A maintainer, I'm the CEO of Techie Tessie :)

oh nice , please assign me the issue then
