### ISSUE TITLE
Design a beautiful home page for techie tessie

### ISSUE THREAD

**Issue by srinjoy-26** [Techie-Tessie/Summer#6]
A beautiful and attractive homepage , please explain the content and stuff I need to display in the home page.
@Tess314

**Comment by Tess314** [comment]
@srinjoy-26 You can include whatever content you wish as long as it is summer-themed :)

**Comment by srinjoy-26** [comment]
> @srinjoy-26 You can include whatever content you wish as long as it is summer-themed :)

Ok bro thanks 🤘

**Comment by srinjoy-26** [comment]
please assign me @Mohasin-Haque

**Comment by Mohasin-Haque** [comment]
Please do it before 10th june.
