### ISSUE TITLE
adding a github repo page

### ISSUE THREAD

**Issue by pizzacode-byte** [Techie-Tessie/Summer#8]
Good morning,

I have seen your project and I am interested in making a contribution.What do you think of adding a page with all your github repos. I can do this with the github API and vanilla JS.I hope you have a great day.

**Comment by Mohasin-Haque** [comment]
Hey, Thanks for your interest but we are taking contributions for summer themed web pages. You can also try that. But for now I can not assign you this issue as our main theme is summer.
